nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro 
      - ./nginx/certs:/etc/nginx/certs:ro  # <--- ADICIONE ESTA LINHA EXATAMENTE ASSIM
    depends_on:
      - faculdade-app
    networks:
      - faculdade-network